### ISSUE TITLE
代码讨论

### ISSUE THREAD

**Issue by BaronZ** [BaronZ/MemoryLeaksDemo#1]
@johnwatsondev 来讨论讨论我这个demo的问题

**Comment by johnwatsondev** [comment]
##### 问题一：

在 [AnonymousClassLeakActivity.java](MemoryLeaksDemo/app/src/main/java/com/zzb/memoryleak/leaks/AnonymousClassLeakActivity.java) 中，内存泄漏的核心原因是静态对象直接或间接持有了 Activity 引用。

`SingletonAnonymousLeak` 是单例对象，其成员变量 `mListeners` 存放了 add 的 Listener 。  
由于 `SingletonAnonymousLeak` 对象会一直在内存中存活，直到应用关闭或者手动释放。`mListeners` 当然也会一直被持有，因此被 add 的 Listener 肯定也被持有。

所以，即使不使用匿名内部类也照样会造成泄漏，正如 `SingletonAnonymousLeak` 中 的 `leak1()` 方法所示：

``` java
private void leak1() {
  SingletonAnonymousLeak.getInstance().setListener(this);
}
```

匿名内部类隐式地持有外部类引用，把匿名内部类 Listener 对象 add 到 `SingletonAnonymousLeak` 的 `mListeners` ，这样 `mListeners` 自然会间接持有 Activity 引用。

##### 问题二：

``` java
//使用lambda可以避免内存泄露，前提是不引用外部类
private void lambdaAvoidLeak(){
  SingletonAnonymousLeak.getInstance().addListener(() -> {
  });
}
```

最好可以解释下原因。

另外这种简单的笔记型的 Demo ，还是不要打广告了，全面深入研究下再说。

谢谢邀请交流。:)

**Comment by BaronZ** [comment]
问题一：这个demo就是来说明内存泄露的场景，没说不使用匿名内部类不会造成内存泄露。
写这个demo就是为了让大家避免一些简单易见的内存泄露，分享出来何乐而不为？
问题二：这个提交记录有写明
https://github.com/BaronZ/MemoryLeaksDemo/commit/23c9f5c7b891b096d6e05dabdcd6168581af493c

**Comment by BaronZ** [comment]
另外我这么写，(单例引用匿名内部类)也是为了明显造成匿名内部类泄漏(不可以？)，这个是为了演示用的，不断进出Activity，让内存一直增加，就是这个意思，另外你看了我那个AsyncTask的内存泄露没？你看了应该就知道意思了吧，那个没有静态引用，那个也可以说明内存泄露啊，只是看task的执行时长啊，但是static我可以一直泄露啊，我要演示，这样是不是更明显说明内存泄露

**Comment by BaronZ** [comment]
你说“大概看了下那个 Demo ，我很佩服足下开源那个代码的勇气。”
你说了这句话，我以为我的代码是有什么低级错误，如果按你说的这些，我还是有勇气开源出来的，我是分享出来给大家，避免一些常见的内存泄露。当然你水平更高的话，也可以写出一些内存泄露的demo出来。
说这些有点讽刺的话，而我又没看到你有更高明的指导，那还是很不爽的

**Comment by johnwatsondev** [comment]
问题一：本来 issue 就是在讨论 Rxjava 使用场景，直接歪楼插一杠子广告。对不起，这里是 Github ，又不是贴吧。  
关于举例的问题，也许应该写个 Wiki 解释清楚为何匿名内部类或者内部类会造成泄漏。

核心问题在于：某些持有了 Activity 引用的对象，其生命周期要比持有的 Activity 对象还长。这才是泄漏的根本原因。

问题二：对不起，让读者去查看 commit 日志，“臣妾”做不到。

**Comment by BaronZ** [comment]
原来你说的是代码问题，现在看来，代码起码不会那么难堪。广告这个就不和你扯了。
确实没写wiki说明。
没要求让读者看commit日志，你说到就发给你看。
